include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"

linter:
  rules:
    avoid_renaming_method_parameters: true
    avoid_returning_null: true
    cascade_invocations: true
    comment_references: true
    iterable_contains_unrelated_type: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: true
    only_throw_errors: true
    package_api_docs: true
    prefer_adjacent_string_concatenation: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    public_member_api_docs: false
    sort_pub_dependencies: false
    unawaited_futures: false
    unnecessary_lambdas: true
